Pandas

Pandas is a powerful Python library for data manipulation and analysis.
It provides data structures like Series (1D) and DataFrame (2D) to handle 
and process data efficiently. Below is an explanation of how to work with 
1D and 2D data in Pandas:

In [2]:
# Panel Data
# data analysis and manipulation
# series (1D) - rows/ columns singularlypip 
# data frame (2D) - table format

Series (1D)

In [3]:
import pandas as pd

# Create a Series from a list
data = [10, 20, 30, 40, 50]
series = pd.Series(data)
print(series)

series = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64
a    10
b    20
c    30
d    40
e    50
dtype: int64


DataFrame (2D)

In [8]:
# Create a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print(df)

# Access a single column (returns a Series)
print('\n=================\n', df['Name'])

# Access multiple columns
print('\n=================\n', df[['Name', 'City']])

# Access a row by index
print('\n=================\n', df.iloc[1])  # Second row (index 1)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

       Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

 Name            Bob
Age              30
City    Los Angeles
Name: 1, dtype: object


List of list

In [19]:
df=pd.DataFrame([[1, 2, 3],["No Data", 22, 23]], columns=['age', 'mark1', 'mark2'])
print(df)
print("\n=======================\n")
# columns must be homogeneous, other wise it will be considered as an object
print(df.dtypes)

       age  mark1  mark2
0        1      2      3
1  No Data     22     23


age      object
mark1     int64
mark2     int64
dtype: object


List of Dictionary

In [20]:
df={"name":["shyam", "Jithu"], "place": ['tcr', 'pkd'], "phone": [911234123, 9177722377]}
df1=pd.DataFrame(df)
print(df1)
print("\n=======================\n")
print(df1.dtypes)

    name place       phone
0  shyam   tcr   911234123
1  Jithu   pkd  9177722377


name     object
place    object
phone     int64
dtype: object


Dictionary of list

In [26]:
df=[{"name": "shyam", "place": 'tcr', "phone": 911234123}, {"name": "Jithu", "place": 'pkd', "phone": 9177722377}]
df2=pd.DataFrame(df)
print(df2)
print("\n=======================\n")
print(df2.dtypes)

print("\n=======================\n")

df=[{"name1": "shyam", "place": 'tcr', "phone1": 911234123}, {"name": "Jithu", "place1": 'pkd', "phone": 9177722377}]
df2=pd.DataFrame(df)
print(df2)
print("\n=======================\n")
print(df2.dtypes)

    name place       phone
0  shyam   tcr   911234123
1  Jithu   pkd  9177722377


name     object
place    object
phone     int64
dtype: object


   name1 place       phone1   name place1         phone
0  shyam   tcr  911234123.0    NaN    NaN           NaN
1    NaN   NaN          NaN  Jithu    pkd  9.177722e+09


name1      object
place      object
phone1    float64
name       object
place1     object
phone     float64
dtype: object


2D array to Dataframe

In [40]:
# 2D array of shape (10, 5) with random numbers b/w 1-50 and convert into dataframe
import numpy as np
array1 = np.random.randint(1,51,(10,5))
print(array1)
print("\n=======================\n")
df3=pd.DataFrame(array1, columns=['a', 'b', 'Column 3', 'c', 'd'])
print(df3)
print("\n=======================\n")

[[ 7  6 19 20 19]
 [31 27 45 28 20]
 [48 14 40 41 26]
 [44 40 44  8  1]
 [16 35 10 47 45]
 [18 39 21  5 27]
 [44 35  2 15  7]
 [11 19  7 39 46]
 [24 45 40 38  2]
 [31  8 11 44 31]]


    a   b  Column 3   c   d
0   7   6        19  20  19
1  31  27        45  28  20
2  48  14        40  41  26
3  44  40        44   8   1
4  16  35        10  47  45
5  18  39        21   5  27
6  44  35         2  15   7
7  11  19         7  39  46
8  24  45        40  38   2
9  31   8        11  44  31




.loc (Location) & .iloc (Integer Location)

In [41]:
print(df3.iloc[-1, 2])
df3.loc[-1, 'Column 3'] = 'python'
print(df3.iloc[-1,2])

11
python


C:\Users\rijok\AppData\Local\Temp\ipykernel_23492\932749947.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'python' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df3.loc[-1, 'Column 3'] = 'python'


In [44]:
# Basic Creation
# 1. Create a DataFrame with the following data with list of list:
# Name   Age  Salary
# ----   ---  ------
# John    25  50000
# Alice   30  60000
# Bob     28  55000
# Assign column names: ["Name", "Age", "Salary"]
# Print the DataFrame.
df={"Name":["John", "Alice", "Bob"], "Age": [25, 30, 28], "Salary": [50000, 60000, 55000]}
df1=pd.DataFrame(df)
print(df1)
print("\n=======================\n")

    Name  Age  Salary
0   John   25   50000
1  Alice   30   60000
2    Bob   28   55000




In [54]:
# 2. Create a DataFrame with student information:
# Columns: "StudentID", "Name", "Marks", "Grade"
# Data:
# 101   Alex     87   A
# 102   Ben      78   B
# 103   Cathy    92   A
# Use pd.DataFrame() with a dictionary.
# Display the first two rows.
df=df={"StudentID": [101, 102, 103], "Name": ["Alex", "Ben", "Cathy"], "Marks": [87, 78, 92], "Grade": ["A", "B", "A"]}
df1=pd.DataFrame(df)
print(df1)
print("\n=======================\n")
print(df1.iloc[0:2])
print("\n=======================\n")

   StudentID   Name  Marks Grade
0        101   Alex     87     A
1        102    Ben     78     B
2        103  Cathy     92     A


   StudentID  Name  Marks Grade
0        101  Alex     87     A
1        102   Ben     78     B




In [56]:
# Using NumPy and Random Data
# 3. Create a DataFrame with 5 rows and 4 columns using random integers between 1 and 100. 
# Assign column names: ["A", "B", "C", "D"].
# ---
# 2. Accessing Data Using iloc
import numpy as np
array1 = np.random.randint(1, 101, (5, 4))
print(array1)
print("\n=======================\n")
df=pd.DataFrame(array1, columns=['A', 'B', 'C', 'D'])
print(df)
print("\n=======================\n")

[[ 45  36  92  75]
 [  4  27  85  79]
 [  1  83  44  52]
 [ 39  82 100  39]
 [ 40  32  67  94]]


    A   B    C   D
0  45  36   92  75
1   4  27   85  79
2   1  83   44  52
3  39  82  100  39
4  40  32   67  94




In [108]:
# 4. From the following DataFrame, extract:
# import pandas as pd
# data = {"A": [10, 20, 30, 40, 50],
#         "B": [5, 15, 25, 35, 45],
#         "C": [100, 200, 300, 400, 500]}
# df = pd.DataFrame(data, index=["Row1", "Row2", "Row3", "Row4", "Row5"])
# The second row using iloc.
# The first and third rows.
# The last two rows.
# The first two columns of the third row.
# The first column of all rows.
data = {"A": [10, 20, 30, 40, 50],
        "B": [5, 15, 25, 35, 45],
        "C": [100, 200, 300, 400, 500]}
df = pd.DataFrame(data, index=["Row1", "Row2", "Row3", "Row4", "Row5"])
print(data)
print("\n=======================\n")
print(df)
print("\n=======================\n")
# print(df.iloc[1])
print(df.loc["Row2"])
print("\n=======================\n")
print(df.iloc[0:3:2])
print("\n=======================\n")
print(df.iloc[[-2,-1]])
print("\n=======================\n")
print(df.iloc[2, :2])
print("\n=======================\n")
print(df.iloc[:,0])

{'A': [10, 20, 30, 40, 50], 'B': [5, 15, 25, 35, 45], 'C': [100, 200, 300, 400, 500]}


       A   B    C
Row1  10   5  100
Row2  20  15  200
Row3  30  25  300
Row4  40  35  400
Row5  50  45  500


A     20
B     15
C    200
Name: Row2, dtype: int64


       A   B    C
Row1  10   5  100
Row3  30  25  300


       A   B    C
Row4  40  35  400
Row5  50  45  500


A    30
B    25
Name: Row3, dtype: int64


Row1    10
Row2    20
Row3    30
Row4    40
Row5    50
Name: A, dtype: int64


In [ ]:
print(df['A'])
print(df[['B', 'A', 'C']])
df['D']=[10, 40, 80, 120, 122]
print(df)
df[['E', 'F', 'G']]=-1
print(df)
if ('E', 'F', 'G' in df.columns):
    df.drop(columns=['E', 'F', 'G'], inplace=True)
print(df)
df.columns # returns column labels
df.index # row names
df.drop('Row2')
df.loc[1]=[12,13,14,15]
print(df)

Row1    10
Row2    20
Row3    30
Row4    40
Row5    50
1       12
Name: A, dtype: int64
       B   A    C
Row1   5  10  100
Row2  15  20  200
Row3  25  30  300
Row4  35  40  400
Row5  45  50  500
1     13  12   14


ValueError: Length of values (5) does not match length of index (6)

In [109]:
df.sort_index
df.reset_index(drop=True, inplace=True)
df['sum_column']=(df['A'] + df['B'])
df.loc[3, 'C']=np.nan
df.rename(columns={"A":"Name", "C":"Marks"}, inplace=True)
print(df)
df.rename(index={0:"first", 1:"second", 3:"third"}, inplace=True)
print(df)

   Name   B  Marks  sum_column
0    10   5  100.0          15
1    20  15  200.0          35
2    30  25  300.0          55
3    40  35    NaN          75
4    50  45  500.0          95
        Name   B  Marks  sum_column
first     10   5  100.0          15
second    20  15  200.0          35
2         30  25  300.0          55
third     40  35    NaN          75
4         50  45  500.0          95


In [139]:
# Exercise: DataFrame Operations in Pandas
# Step 1: Create a DataFrame
# Create a DataFrame with the following data:
data = {"ID": [1, 2, 3, 4, 5],
        "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
        "Age": [25, 30, 35, 40, 28],
        "City": ["New York", "Chicago", "Boston", "Seattle", "Austin"],
        "Salary": [50000, 60000, 55000, 70000, 65000]}
df = pd.DataFrame(data)
print('\n=================\n', df,'\n=================\n')



    ID     Name  Age      City  Salary
0   1    Alice   25  New York   50000
1   2      Bob   30   Chicago   60000
2   3  Charlie   35    Boston   55000
3   4    David   40   Seattle   70000
4   5     Emma   28    Austin   65000 



In [159]:
# Step 2: Locate Specific Rows and Columns
# 1. Select and print the row where Name is "Charlie".
# 2. Retrieve the Name and Salary columns for all employees.
print('\n=================\n', df.iloc[2, :],'\n=================\n')
print('\n=================\n', df["Name", "Salary"][df['Name']=='Charlie'],'\n=================\n')
print('\n=================\n', df.loc[:,["Name", "Salary"]],'\n=================\n')


 ID                     3
Name             Charlie
City              Boston
Annual_Income      55000
Experience             8
Name: 2, dtype: object 



KeyError: ('Name', 'Salary')

In [137]:
# Step 3: Drop Columns and Rows
# 1. Drop the City column without modifying the original DataFrame.
# 2. Drop the row where ID is 3 permanently.
df.drop(columns=['City'])
df.drop(index=2, inplace=True)
print(df)


   ID   Name  Age      City  Salary
0   1  Alice   25  New York   50000
1   2    Bob   30   Chicago   60000
3   4  David   40   Seattle   70000
4   5   Emma   28    Austin   65000


In [ ]:
# Step 4: Add a New Column
# 1. Add a new column Experience with values [2, 5, 8, 10, 4].
df['Experience'] = [2, 5, 8, 10, 4]
print('\n=================\n', df,'\n=================\n')


    ID     Name  Age      City  Salary  Experience
0   1    Alice   25  New York   50000           2
1   2      Bob   30   Chicago   60000           5
2   3  Charlie   35    Boston   55000           8
3   4    David   40   Seattle   70000          10
4   5     Emma   28    Austin   65000           4 



In [147]:
# Step 5: Understand the inplace Parameter
# 1. Drop the Age column using inplace=True.
# 2. Try accessing the Age column again.
if ('Age' in df.columns):
    df.drop(columns='Age', inplace=True)
df['Age']

KeyError: 'Age'

In [ ]:
# Step 6: Reset Index
# 1. Reset the index after dropping the row and store it back in the same DataFrame.
df.reset_index(drop=True, inplace=True)
print('\n=================\n', df,'\n=================\n')


    ID     Name      City  Salary  Experience
0   1    Alice  New York   50000           2
1   2      Bob   Chicago   60000           5
2   3  Charlie    Boston   55000           8
3   4    David   Seattle   70000          10
4   5     Emma    Austin   65000           4 



In [157]:
# Step 7: Call Multiple Columns
# 1. Select and print only Name, Salary, and Experience.
print('\n=================\n', df[['Name', 'Salary', 'Experience']],'\n=================\n')

# Step 8: Rename Columns
# 1. Rename Salary to Annual_Income and Experience to Years_of_Experience.
df.rename(columns={"Salary":"Annual_Income"}, inplace=True)
print('\n=================\n', df,'\n=================\n')


       Name  Salary  Experience
0    Alice   50000           2
1      Bob   60000           5
2  Charlie   55000           8
3    David   70000          10
4     Emma   65000           4 


    ID     Name      City  Annual_Income  Experience
0   1    Alice  New York          50000           2
1   2      Bob   Chicago          60000           5
2   3  Charlie    Boston          55000           8
3   4    David   Seattle          70000          10
4   5     Emma    Austin          65000           4 



In [1]:
import pandas as pd
data={'ID':[1,2,3,4,5],'Name':['Alice','Bob','Charlie','David','Emma'],'Age':[25,30,35,40,28],'City':['New York','Chicago','Boston','Seattle','Austin'],'Salary':[50000,60000,55000,70000,65000]}
df=pd.DataFrame(data)
print(df)
#another method for rename columns and rows
df.columns=['a','b','c','d','e']
df.index
df.index=range(100,105)
print(df)
#but this method mainly used for renaming all columns or rows
df.shape
df.dtypes
df.size
#to convert 1D array to series 
lst=[1,2,3,4,5]
series1=pd.Series(lst)
print(series1)
series1[2]=100
print(series1)
series1[:]=10
print(series1)

   ID     Name  Age      City  Salary
0   1    Alice   25  New York   50000
1   2      Bob   30   Chicago   60000
2   3  Charlie   35    Boston   55000
3   4    David   40   Seattle   70000
4   5     Emma   28    Austin   65000
     a        b   c         d      e
100  1    Alice  25  New York  50000
101  2      Bob  30   Chicago  60000
102  3  Charlie  35    Boston  55000
103  4    David  40   Seattle  70000
104  5     Emma  28    Austin  65000
0    1
1    2
2    3
3    4
4    5
dtype: int64
0      1
1      2
2    100
3      4
4      5
dtype: int64
0    10
1    10
2    10
3    10
4    10
dtype: int64


In [2]:
lst=[1,2,3,4,5]
series1=pd.Series(lst)
print(series1)
#to change index values
series1.index=range(10,15)
print(series1)
series1[2]=100 #since it contains no data with index the new data with index 2 will be added
print(series1)
series1.iloc[2]=100
print(series1)

0    1
1    2
2    3
3    4
4    5
dtype: int64
10    1
11    2
12    3
13    4
14    5
dtype: int64
10      1
11      2
12      3
13      4
14      5
2     100
dtype: int64
10      1
11      2
12    100
13      4
14      5
2     100
dtype: int64


In [ ]:
import pandas as pd
data={'ID':[1,2,3,4,5],'Name':['Alice','Bob','Charlie','David','Emma'],'Age':[25,30,35,40,28],'City':['New York','Chicago','Boston','Seattle','Austin'],'Salary':[50000,60000,55000,70000,65000]}
df=pd.DataFrame(data)
print(df)
#to covert a datframe to a 2D array
print(df.values)
type(df.values)

   ID     Name  Age      City  Salary
0   1    Alice   25  New York   50000
1   2      Bob   30   Chicago   60000
2   3  Charlie   35    Boston   55000
3   4    David   40   Seattle   70000
4   5     Emma   28    Austin   65000
[[1 'Alice' 25 'New York' 50000]
 [2 'Bob' 30 'Chicago' 60000]
 [3 'Charlie' 35 'Boston' 55000]
 [4 'David' 40 'Seattle' 70000]
 [5 'Emma' 28 'Austin' 65000]]


numpy.ndarray